-- Require files

require('awash.mappings')
require('awash.plugins')
require('awash.lsp')

require('awash.nvim-tree')
require('awash.lualine')
require('awash.treesitter')
require('awash.luasnip')
require('awash.nvim-devicons')
require('awash.cmp')
require('awash.autopairs')
require('awash.bufferline')
require('awash.closetags')
require('awash.commenter')
require('awash.gitgutter')
require('awash.indent-blank-line')
require('awash.tagbar')
require('awash.toggleterm')
require('awash.trouble-nvim')
require('awash.colorscheme')
require('awash.error-reporting')
require('awash.better-escape')
require('awash.behavior')
require('awash.visuals')
