-- Require files

require('user.mappings')
require('user.options')
require('user.plugins')
require('user.lsp')

require('user.nvim-tree')
require('user.lualine')
require('user.treesitter')
require('user.luasnip')
require('user.nvim-devicons')
require('user.cmp')
require('user.autopairs')
require('user.bufferline')
require('user.closetags')
require('user.commenter')
require('user.gitgutter')
require('user.indent-blank-line')
require('user.tagbar')
require('user.toggleterm')
require('user.trouble-nvim')
require('user.colorscheme')
require('user.error-reporting')

